src/java/co/gov/transporte/controlador/ViajeController.java
package co.gov.transporte.controlador;

import co.gov.transporte.entidades.Viaje;
import co.gov.transporte.controlador.util.JsfUtil;
import co.gov.transporte.controlador.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("viajeController")
@SessionScoped
public class ViajeController implements Serializable {

    @EJB
    private co.gov.transporte.controlador.ViajeFacade ejbFacade;
    private List<Viaje> items = null;
    private Viaje selected;

    public ViajeController() {
    }

    public Viaje getSelected() {
        return selected;
    }

    public void setSelected(Viaje selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ViajeFacade getFacade() {
        return ejbFacade;
    }

    public Viaje prepareCreate() {
        selected = new Viaje();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("ViajeCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("ViajeUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("ViajeDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Viaje> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Viaje getViaje(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Viaje> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Viaje> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Viaje.class)
    public static class ViajeControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ViajeController controller = (ViajeController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "viajeController");
            return controller.getViaje(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Viaje) {
                Viaje o = (Viaje) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Viaje.class.getName()});
                return null;
            }
        }

    }

}

web/viaje/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ViajeCreateDlg" widgetVar="ViajeCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateViajeTitle}">
            <h:form id="ViajeCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{viajeController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateViajeLabel_id}" for="id" />
                        <p:inputText id="id" value="#{viajeController.selected.id}" title="#{bundle.CreateViajeTitle_id}" required="true" requiredMessage="#{bundle.CreateViajeRequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle.CreateViajeLabel_horasalida}" for="horasalida" />
                        <p:calendar id="horasalida" pattern="MM/dd/yyyy HH:mm:ss" value="#{viajeController.selected.horasalida}" title="#{bundle.EditViajeTitle_horasalida}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateViajeLabel_horallegada}" for="horallegada" />
                        <p:calendar id="horallegada" pattern="MM/dd/yyyy HH:mm:ss" value="#{viajeController.selected.horallegada}" title="#{bundle.EditViajeTitle_horallegada}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateViajeLabel_placabuseta}" for="placabuseta" />
                        <p:selectOneMenu id="placabuseta" value="#{viajeController.selected.placabuseta}" >
                            <f:selectItems value="#{busetaController.itemsAvailableSelectOne}"
                                           var="placabusetaItem"
                                           itemValue="#{placabusetaItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateViajeLabel_idultimoparadero}" for="idultimoparadero" />
                        <p:selectOneMenu id="idultimoparadero" value="#{viajeController.selected.idultimoparadero}" >
                            <f:selectItems value="#{paraderoController.itemsAvailableSelectOne}"
                                           var="idultimoparaderoItem"
                                           itemValue="#{idultimoparaderoItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateViajeLabel_idruta}" for="idruta" />
                        <p:selectOneMenu id="idruta" value="#{viajeController.selected.idruta}" >
                            <f:selectItems value="#{rutaController.itemsAvailableSelectOne}"
                                           var="idrutaItem"
                                           itemValue="#{idrutaItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{viajeController.create}" value="#{bundle.Save}" update="display,:ViajeListForm:datalist,:growl" oncomplete="handleSubmit(args,'ViajeCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ViajeCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/viaje/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ViajeEditDlg" widgetVar="ViajeEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditViajeTitle}">
            <h:form id="ViajeEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{viajeController.selected != null}">
                        <p:outputLabel value="#{bundle.EditViajeLabel_id}" for="id" />
                        <p:inputText id="id" value="#{viajeController.selected.id}" title="#{bundle.EditViajeTitle_id}" required="true" requiredMessage="#{bundle.EditViajeRequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle.EditViajeLabel_horasalida}" for="horasalida" />
                        <p:calendar id="horasalida" pattern="MM/dd/yyyy HH:mm:ss" value="#{viajeController.selected.horasalida}" title="#{bundle.EditViajeTitle_horasalida}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.EditViajeLabel_horallegada}" for="horallegada" />
                        <p:calendar id="horallegada" pattern="MM/dd/yyyy HH:mm:ss" value="#{viajeController.selected.horallegada}" title="#{bundle.EditViajeTitle_horallegada}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.EditViajeLabel_placabuseta}" for="placabuseta" />
                        <p:selectOneMenu id="placabuseta" value="#{viajeController.selected.placabuseta}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{busetaController.itemsAvailableSelectOne}"
                                           var="placabusetaItem"
                                           itemValue="#{placabusetaItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditViajeLabel_idultimoparadero}" for="idultimoparadero" />
                        <p:selectOneMenu id="idultimoparadero" value="#{viajeController.selected.idultimoparadero}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{paraderoController.itemsAvailableSelectOne}"
                                           var="idultimoparaderoItem"
                                           itemValue="#{idultimoparaderoItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditViajeLabel_idruta}" for="idruta" />
                        <p:selectOneMenu id="idruta" value="#{viajeController.selected.idruta}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{rutaController.itemsAvailableSelectOne}"
                                           var="idrutaItem"
                                           itemValue="#{idrutaItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{viajeController.update}" value="#{bundle.Save}" update="display,:ViajeListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ViajeEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ViajeEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/viaje/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListViajeTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="ViajeListForm">
                <p:panel header="#{bundle.ListViajeTitle}">
                    <p:dataTable id="datalist" value="#{viajeController.items}" var="item"
                                 selectionMode="single" selection="#{viajeController.selected}"
                                 paginator="true"
                                 rowKey="#{item.id}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListViajeTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListViajeTitle_horasalida}"/>
                            </f:facet>
                            <h:outputText value="#{item.horasalida}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListViajeTitle_horallegada}"/>
                            </f:facet>
                            <h:outputText value="#{item.horallegada}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListViajeTitle_placabuseta}"/>
                            </f:facet>
                            <h:outputText value="#{item.placabuseta}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListViajeTitle_idultimoparadero}"/>
                            </f:facet>
                            <h:outputText value="#{item.idultimoparadero}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListViajeTitle_idruta}"/>
                            </f:facet>
                            <h:outputText value="#{item.idruta}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{viajeController.prepareCreate}" update=":ViajeCreateForm" oncomplete="PF('ViajeCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":ViajeViewForm" oncomplete="PF('ViajeViewDialog').show()" disabled="#{empty viajeController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":ViajeEditForm" oncomplete="PF('ViajeEditDialog').show()" disabled="#{empty viajeController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{viajeController.destroy}" update=":growl,datalist" disabled="#{empty viajeController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/viaje/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ViajeViewDlg" widgetVar="ViajeViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewViajeTitle}">
            <h:form id="ViajeViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{viajeController.selected != null}">
                        <h:outputText value="#{bundle.ViewViajeLabel_id}"/>
                        <h:outputText value="#{viajeController.selected.id}" title="#{bundle.ViewViajeTitle_id}"/>
                        <h:outputText value="#{bundle.ViewViajeLabel_horasalida}"/>
                        <h:outputText value="#{viajeController.selected.horasalida}" title="#{bundle.ViewViajeTitle_horasalida}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewViajeLabel_horallegada}"/>
                        <h:outputText value="#{viajeController.selected.horallegada}" title="#{bundle.ViewViajeTitle_horallegada}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewViajeLabel_placabuseta}"/>
                        <h:outputText value="#{viajeController.selected.placabuseta}" title="#{bundle.ViewViajeTitle_placabuseta}"/>
                        <h:outputText value="#{bundle.ViewViajeLabel_idultimoparadero}"/>
                        <h:outputText value="#{viajeController.selected.idultimoparadero}" title="#{bundle.ViewViajeTitle_idultimoparadero}"/>
                        <h:outputText value="#{bundle.ViewViajeLabel_idruta}"/>
                        <h:outputText value="#{viajeController.selected.idruta}" title="#{bundle.ViewViajeTitle_idruta}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="ViajeViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>